# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions. 

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
zeros_array = np.zeros(10)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [3]:
ones_array = np.ones(10)
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [4]:
fives_array = np.ones(10) * 5
print(fives_array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Create an array of the integers from 10 to 50

In [5]:
array_10_to_50 = np.arange(10, 51)
print(array_10_to_50)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [6]:
even_array = np.arange(10, 51, 2)
print(even_array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
matrix = np.arange(0, 9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [8]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [9]:
random_number = np.random.rand()
print(random_number)

0.8307074689651303


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [10]:
random_numbers = np.random.randn(25)
print(random_numbers)

[ 1.03309315 -1.18922151  0.21407803  0.87578701  0.93174852 -1.07732476
  0.77027    -2.11761806 -0.61258492 -0.9278346  -0.17539456  1.687907
  0.29303305 -0.26913734 -0.82387173  0.74230539  1.37968236  0.01184558
 -0.53572448 -0.25740827  0.33233295  0.38408108 -0.28617555 -1.2236015
 -0.66655632]


#### Create the following matrix:

In [11]:
mat = np.array([[ 1,  2,  3,  4,  5],
                [ 6,  7,  8,  9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25]])

print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [12]:
linearly_spaced_points = np.linspace(0, 1, 20)
print(linearly_spaced_points)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


### Now do the following

#### Get the sum of all the values in mat

In [13]:
sum_of_values = np.sum(mat)
print(sum_of_values)

325


#### Get the standard deviation of the values in mat

In [14]:
std_dev = np.std(mat)
print(std_dev)

7.211102550927978


#### Get the sum of all the columns in mat

In [15]:
column_sums = np.sum(mat, axis=0)
print(column_sums)

[55 60 65 70 75]
